#!/bin/bash

ROOT=/home/big_data_contest


THE_CONFIG=$ROOT/the_config


THE_CODE=$ROOT/the_code

CODE_STAT=$THE_CODE/stat


THE_DATA=$ROOT/the_data

DATA_CONTEST=$THE_DATA/contest_data

DATA_TRAINING=$THE_DATA/training_data

DATA_TEST=$TEH_DATA/test_data


THE_LOG=$ROOT/the_log

LOG_STAT=$THE_LOG/stat
